/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f0f1ee',
        'surface-bright': '#f9faf6',
        'tertiary-container': '#5a302f',
        'accent-fern': '#40916C',
        'on-primary-fixed-variant': '#274e3d',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#331111',
        'inverse-surface': '#2f312f',
        'on-surface': '#1a1c1a',
        'on-primary-container': '#86af99',
        'surface-tint': '#3f6653',
        'on-error-container': '#93000a',
        'primary-container': '#1b4332',
        'on-tertiary-container': '#d29895',
        'outline': '#717973',
        'on-tertiary': '#ffffff',
        'border-default': '#D1D5DB',
        'highlight-sage': '#74C69D',
        'status-danger-bg': '#FEE2E2',
        'on-error': '#ffffff',
        'on-primary-fixed': '#002114',
        'surface-container-lowest': '#ffffff',
        'background-mint': '#F0FAF4',
        'status-danger': '#EF4444',
        'on-primary': '#ffffff',
        'primary': '#012d1d',
        'tertiary': '#401b1b',
        'primary-fixed-dim': '#a5d0b9',
        'status-success': '#1B4332',
        'inverse-primary': '#a5d0b9',
        'status-warning': '#F59E0B',
        'secondary': '#2c694e',
        'primary-fixed': '#c1ecd4',
        'on-tertiary-fixed-variant': '#673a39',
        'surface-container-highest': '#e2e3e0',
        'surface-container-low': '#f3f4f1',
        'surface': '#f9faf6',
        'surface-variant': '#e2e3e0',
        'background': '#f9faf6',
        'outline-variant': '#c1c8c2',
        'status-success-bg': '#D8F3DC',
        'on-secondary-container': '#316e52',
        'surface-container': '#eeeeeb',
        'on-background': '#1a1c1a',
        'text-main': '#111827',
        'surface-dim': '#dadad7',
        'status-warning-bg': '#FEF9C3',
        'tertiary-fixed-dim': '#f5b7b4',
        'on-secondary-fixed-variant': '#0e5138',
        'on-surface-variant': '#414844',
        'error': '#ba1a1a',
        'secondary-fixed-dim': '#95d4b3',
        'text-muted': '#6B7280',
        'tertiary-fixed': '#ffdad8',
        'secondary-fixed': '#b1f0ce',
        'surface-container-high': '#e8e8e5',
        'surface-mist': '#D8F3DC',
        'on-secondary-fixed': '#002114',
        'on-secondary': '#ffffff',
        'secondary-container': '#aeeecb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-md': '16px',
        'container-padding': '24px',
        'sidebar-width': '240px',
        'topbar-height': '64px',
        'auth-card-width': '400px',
      },
      fontFamily: {
        'headline-3': ['Newsreader'],
        'headline-1': ['Newsreader'],
        'headline-2': ['Newsreader'],
        label: ['Inter'],
        'body-sm': ['Inter'],
        body: ['Inter'],
        tagline: ['Newsreader'],
      },
      fontSize: {
        'headline-3': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-1': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-2': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        label: ['12px', { lineHeight: '1', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        body: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        tagline: ['14px', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}